# Taller 4

1.Implemente un método que retorne la subsecuencia común más larga (SCL) apartir de la matriz C construida por el algoritmo de PD que calcula la longitud de la SCL.

In [19]:
import numpy as np
import math

import pylab as pl
%matplotlib inline

global var

def metodo1_LCS(auxX,auxY):
    
    global var
    
    var = np.ones((len(auxX)+1,len(auxY)+1))*-1
    lcs3(auxX,auxY,len(auxX),len(auxY))
    
    return var[len(auxX)-1,len(auxY)-1], var
    

def metodo2_LCS(x,y,i,j):
    
    global var
    
    if var[i,j] == -1:
        if i == 0 or j == 0:
            var[i,j] = 0
            
        else:
            if x[i-1]==y[j-1]:
                var[i,j] = metodo2_LCS(x,y,i-1,j-1)+1
                
            else:
                var[i,j] = max(metodo2_LCS(x,y,i-1,j),metodo2_LCS(x,y,i,j-1))
                
    return var[i,j]


def metodo3_cadenaLCS(auxX,auxY,var):
    
    j=len(auxY)
    i=len(auxX)
    ca=''
    
    while(var[i][j]>0 and i >= 0 and j >=0):
        
        if(var[i][j-1] == var[i][j]):
            j=j-1;
            continue;
            
        if(var[i-1][j] == var[i][j] ):
            i=i-1;
            continue;
            
        val = auxY[j-1]
        ca+=val;
        
        i=i-1;
        j=j-1;
        
        cb=ca[::-1]
    
    print (cb);

In [20]:
print "La subsecuencia común más larga, es: "
print
metodo3_cadenaLCS('KSDJKBF','DDJBKPL',lcs_mat)
print
len_lcs, lcs_mat = metodo1_LCS('ABCDEER','ABCDEFG')

print (lcs_mat);


La subsecuencia común más larga, es: 

DDJBK

[[ 0. -1.  0.  0.  0.  0.  0.  0.]
 [-1.  1.  1.  1.  1.  1.  1.  1.]
 [ 0.  1.  2.  2.  2.  2.  2.  2.]
 [ 0.  1.  2.  3.  3.  3.  3.  3.]
 [ 0.  1.  2.  3.  4.  4.  4.  4.]
 [ 0.  1.  2.  3.  4.  5.  5.  5.]
 [ 0.  1.  2.  3.  4.  5.  5.  5.]
 [ 0.  1.  2.  3.  4.  5.  5.  5.]]


2.Para el problema del corte de la barilla (Notebook):

2.1.Implemente un método para determinar los cortes que se deben realizar a partir de la solución de PD que encuentra el valor de la solución óptima.


In [32]:
def cut_rodR(aux1, aux2):
    
    if aux2==0:
        return 0
    
    aux3 = float('-inf')
    
    for recorr in range(aux2):
        #print recorr
        aux3 = max(aux3, aux1[recorr] + cut_rodR(aux1, aux2-1-recorr))
        
    return aux3

In [33]:
aux1 = [2,56,35,21,45,85,9,65,25,45]
rta = cut_rodR(aux1,10)

print "El valor de la solución óptima es: "
print (rta)

El valor de la solución óptima es: 
280


3.Implemente, describa y analice un algoritmo de PD para calcular la distancia de edición entre dos cadenas. (Cormen, problem 15-5)

In [27]:
cadena1 = ['a','n','a','l','i','s','i','s']
cadena2 = ['a','l','g','o','r','i','t','m','o','s']

In [28]:
def edicionDistancia(c1,c2):
    
    
    cadena1 =  len(c1)+1
    cadena2 =  len(c2)+1
    C = np.zeros((cadena1,cadena2))
    
    for i in range(0,len(c1)+1):
        C[i,0] = i        
    for j in range(0,len(c2)+1):
        C[0,j] = j            
    for i in range(1, len(c1)+1):
        for j in range(1, len(c2)+1):
            
            if (c1[i-1] == c2[j-1]):
                C[i,j] = C[i-1,j-1]
                
            else:
                C[i,j] = min( C[i-1,j-1] + 1 , C[i-1,j] + 1 , C[i,j-1] + 1 )
    
    return C[len(c1),len(c2)]

In [30]:

cadenaFinal = edicionDistancia(cadena1,cadena2)

print "La distancia de edción entre cadena1 y cadena2 es: "
print cadenaFinal

La distancia de edción entre cadena1 y cadena2 es: 
7.0


4.En el rio atrato hay n embarcaderos, en cada uno de ellos se puede alquilar un bote para realizar un viaje rio abajo a otro embarcadero. Existe una tabla de tarifas que indica el costo del viaje del embarcadero i al j, para i, j = 1,2,...,n  (i<j), puede pasar que un viaje de i a j sea más caro que una serie de viajes sucesivos intermedios, no hay un costo asociado a cambiar de bote en algún embarcadero. El problema consiste en diseñar un algoritmo de PD que determine el costo mínimo para cada par de puntos i,j.

In [22]:
def minimo(c,i,j,tarifa,nPuertos):
    k=0
    aux=j
    for k in range(i+1,nPuertos):
        #print("en aux: ",aux)
        #print(tarifa[i,k])
        aux=min(aux,tarifa[i,k]+c[k][j])
    return aux


def costos(nPuertos,tarifa):
    c=np.zeros((nPuertos,nPuertos))
    diagonal= nPuertos
    for diagonal in range (1, nPuertos-1):
        for i in range(1,nPuertos-diagonal):
            num=int(i+diagonal);
            #print (num)
            c[i][num]= minimo(c,i,i+diagonal,tarifa,nPuertos)
            #print(c[i][num])
    return c

In [23]:
tarifa= np.matrix('0 5 6 3 15;0 0 5 6 7;0 0 0 10 15;0 0 0 0 12; 0 0 0 0 0 ')
print (tarifa)
c=costos(5,tarifa)
print (c)

[[ 0  5  6  3 15]
 [ 0  0  5  6  7]
 [ 0  0  0 10 15]
 [ 0  0  0  0 12]
 [ 0  0  0  0  0]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  2.  3.  4.]
 [ 0.  0.  0.  3.  4.]
 [ 0.  0.  0.  0.  4.]
 [ 0.  0.  0.  0.  0.]]
